version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: create-react-app
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: ejs
    versions:
    - 3.1.5
